### ISSUE TITLE
Add wildcard(s) to Leader sequence

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope-Leader#10]
After a [discussion on the forum](https://community.keyboard.io/t/trouble-with-leader-sequences/1684/9?u=merlin), I had the idea to use `Key_NoKey` as a wildcard in Leader sequences, so whatever `Key` value was entered could be used as an argument to the function called. Perhaps this would be limited to a single wildcard value, which would need to be the last key in the sequence in order to keep it from getting too complex (that would certainly work for the one use case we have so far), but maybe it's not so difficult to make it more general. If only a single wildcard is supported, and it must come last in the sequence, it could also be used as a sentinel value. Again, I don't know if that would help.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#406.
