### ISSUE TITLE
Allow single leader key sequences

### ISSUE THREAD

**Issue by Llamalland** [keyboardio/Kaleidoscope-Leader#11]
Would be great if a leader sequence could consist of only that leader key.

**Comment by gedankenexperimenter** [comment]
Wouldn't that be equivalent to a Kaleidoscope-Macros key?

**Comment by Llamalland** [comment]
On its own, yes, but how I want it, no. What I want it for is so leader + letter gets one behaviour (specifically, full stop, space, capital letter) and leader + anything else doesn't match any sequence and reverts to just that leader key's desired behaviour (in particular, a full stop).

**Comment by gedankenexperimenter** [comment]
For that specific use case, I think the "wildcard" idea (#10) would do the trick, if it's not too difficult to implement. In fact, a whole mini-plugin could probably do that without too much code.

**Comment by Llamalland** [comment]
That could be another way of doing it, yes. But it might be simpler to allow single leader sequences for some use cases, and there might be uses for it which aren't covered by that idea.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#405.
