### ISSUE TITLE
Error when attempting to include Kaleidoscope-Leader

### ISSUE THREAD

**Issue by Soares** [keyboardio/Kaleidoscope-Leader#5]
When I attempt to use this plugin, I get the following error message:

    /.../Arduino-Boards/libraries/Kaleidoscope-Leader/src/Kaleidoscope/Leader.h:29:61: error: too many initializers for 'Key'
    > #define LEADER_DICT(...) { __VA_ARGS__, {{Key_NoKey}, NULL} }
                                                                  ^

I'm likely doing something silly, but I can't quite figure out what. Is this plugin still working for you?

**Comment by algernon** [comment]
Yep, still works. Can you show me how you are trying to use the plugin?

**Comment by Soares** [comment]
I'm no longer having this issue. (I stopped trying to use Leader, and now, when I try it, it works.) I'm not sure what was up, but I'm going to go ahead and close the issue.
