### ISSUE TITLE
Leader needs to be released before it starts a sequence

### ISSUE THREAD

**Issue by Llamalland** [keyboardio/Kaleidoscope-Leader#9]
Would it be possible to allow leader sequences to be started by Leader(x)Down rather than Leader(x)Up?

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#407.
